### ISSUE TITLE
之前还行的，现在有如下报错，没有加token以外的参数

### ISSUE THREAD

**Issue by 14790897** [vvbbnn00/qndxxAutoStudy#7]
INFO:root:正在尝试提交记录...
INFO:root:学习失败，返回信息：{"status": 500, "message": "传递了无效的参数: [ ]", "result": null, "debug": "'#0 /data/nginx/html/YunBanOS/src/main/com/yunban/web/request/ParameterValidatorImpl.0.1.php(94): com\\\\yunban\\\\web\\\\request\\\\ParameterValidatorImpl->validObjectParameter(\\'\\\\xE5\\\\x8F\\\\x82\\\\xE6\\\\x95\\\\xB0\\', Object(stdClass), \\'com\\\\\\\\yunban\\\\\\\\yout...\\')\n#1 /data/nginx/html/YunBanOS/src/main/com/yunban/mvc/DispatcherServletImpl.php(86): com\\\\yunban\\\\web\\\\request\\\\ParameterValidatorImpl->valid(Object(com\\\\yunban\\\\youth\\\\ctrl\\\\UserAPIController), Object(com\\\\yunban\\\\reflect2\\\\ReflectionMethod), Object(com\\\\yunban\\\\mvc\\\\annotation\\\\Servlet), \\'/user-api/cours...\\')\n#2 /data/nginx/html/YunBanOS/src/main/com/yunban/mvc/Application.php(100): com\\\\yunban\\\\mvc\\\\DispatcherServletImpl->processRequest(\\'POST\\', \\'/user-api/cours...\\')\n#3 /data/nginx/html/qcsh/youth-learning/cgi-bin.php(22): com\\\\yunban\\\\mvc\\\\Application::main(\\'/data/nginx/htm...\\')\n#4 {main}'"}

**Comment by 14790897** [comment]
```
python .\script.py eyJhcHBpZCI6Ind4YTY5M2Y0MTI3Y2M5M2ZhZCIsIm9wZW5pZCI6Im9rTXFzam5Lb2dvT0xTdVQ1QUx4cW1OQUtaS0kiLCJuaWNrbmFtZSI6IiVFNyU4MSVBQ2wlMjB3JTIwJTIwcSIsImhlYWRpbWciOiJodHRwczovL3RoaXJkd3gucWxvZ28uY24vbW1vcGVuL3ZpXzMyL2lhR0RpYkR6QUF2M2dremliM2licmNtcGFXZ1YwaWI2c3JMUGdUcjB4eUtna1N5NmNieWpSTkxSZ2dUMW01d2V4dDVuS2liMjVQTnZtRGVqZnhKSzdMOU9QR3Z3LzEzMiIsInRpbWUiOiIxNzAxMDc0Nzk2Iiwic291cmNlIjoiY29tbW9uIiwic2lnbiI6IjJFMEI3RDQ5MjRFN0VCODhEQjNCNDhDNTEzRkRBOTU1IiwidCI6IjE3MDEwNzQ3OTYifQ==
```
这个token应该没什么用吧，我直接贴出来了

**Comment by vvbbnn00** [comment]
![image](https://github.com/vvbbnn00/qndxxAutoStudy/assets/46409975/a43444b3-6b0c-4344-a721-ba35b014a8ab)

你好，通过提供的token测试，并没有出现相关错误。您可以尝试使用最新版的脚本重试一下，若问题仍然出现，欢迎继续与我联系。

另外，`token`可能会暴露您的个人信息，不建议在`issue`中公开，已为您删除

**Comment by 14790897** [comment]
我放出全部过程，大佬等会再帮我把这个评论删除
```
PS C:\git-program\qndxxAutoStudy> python .\script.py eyJhcHBpZCI6Ind4YTY5M2Y0MTI3Y2M5M2ZhZCIsIm9wZW5pZCI6Im9rTXFzam5Lb2dvT0xTdVQ1QUx4cW1OQUtaS0kiLCJuaWNrbmFtZSI6IiVFNyU4MSVBQ2wlMjB3JTIwJTIwcSIsImhlYWRpbWciOiJodHRwczovL3RoaXJkd3gucWxvZ28uY24vbW1vcGVuL3ZpXzMyL2lhR0RpYkR6QUF2M2dremliM2licmNtcGFXZ1YwaWI2c3JMUGdUcjB4eUtna1N5NmNieWpSTkxSZ2dUMW01d2V4dDVuS2liMjVQTnZtRGVqZnhKSzdMOU9QR3Z3LzEzMiIsInRpbWUiOiIxNzAxMDc0Nzk2Iiwic291cmNlIjoiY29tbW9uIiwic2lnbiI6IjJFMEI3RDQ5MjRFN0VCODhEQjNCNDhDNTEzRkRBOTU1IiwidCI6IjE3MDEwNzQ3OTYifQ==
INFO:root:开始学习...
INFO:root:登录成功, AccessToken=101DC57D-50BE-455F-A182-6705F37819D1
INFO:root:最后一次学习的信息如下
INFO:root:{
    "nid": "N0001001600191017",
    "cardNo": "刘玮卿",
    "subOrg": null,
    "nodes": [
        {
            "id": "N0001",
            "title": "高校系统",
            "type": "高校"
        },
        {
            "id": "N00010016",
            "title": "上海师范大学",
            "type": "高校"
        },
        {
            "id": "N000100160019",
            "title": "上海师范大学研究生工作",
            "type": "高校"
        },
        {
            "id": "N0001001600191017",
            "title": "信息与机电工程学院研究生团总支",
            "type": null
        }
    ]
}
WARNING:root:未指定组织ID，将使用最后一次学习的组织ID
WARNING:root:未指定姓名/学号/工号，将使用最后一次学习的信息
INFO:root:正在尝试提交记录...
INFO:root:学习失败，返回信息：{"status": 500, "message": "传递了无效的参数: [ ]", "result": null, "debug": "'#0 /data/nginx/html/YunBanOS/src/main/com/yunban/web/request/ParameterValidatorImpl.0.1.php(94): com\\\\yunban\\\\web\\\\request\\\\ParameterValidatorImpl->validObjectParameter(\\'\\\\xE5\\\\x8F\\\\x82\\\\xE6\\\\x95\\\\xB0\\', Object(stdClass), \\'com\\\\\\\\yunban\\\\\\\\yout...\\')\n#1 /data/nginx/html/YunBanOS/src/main/com/yunban/mvc/DispatcherServletImpl.php(86): com\\\\yunban\\\\web\\\\request\\\\ParameterValidatorImpl->valid(Object(com\\\\yunban\\\\youth\\\\ctrl\\\\UserAPIController), Object(com\\\\yunban\\\\reflect2\\\\ReflectionMethod), Object(com\\\\yunban\\\\mvc\\\\annotation\\\\Servlet), \\'/user-api/cours...\\')\n#2 /data/nginx/html/YunBanOS/src/main/com/yunban/mvc/Application.php(100): com\\\\yunban\\\\mvc\\\\DispatcherServletImpl->processRequest(\\'POST\\', \\'/user-api/cours...\\')\n#3 /data/nginx/html/qcsh/youth-learning/cgi-bin.php(22): com\\\\yunban\\\\mvc\\\\Application::main(\\'/data/nginx/htm...\\')\n#4 {main}'"}    
```

**Comment by 14790897** [comment]
代码是最新的

**Comment by vvbbnn00** [comment]
你好，经过尝试，仍然无法复现相关问题，是否方便提供一下您这里的源代码、python版本和网络环境？

若不方便在issue中提供，可以发送至我的邮箱：vvbbnn00@foxmail.com

谢谢

**Comment by 14790897** [comment]
等一下，GitHub action的运行结果可能和大佬之前运行的结果是一样的，那看来是我的问题

**Comment by 14790897** [comment]
Notice:  A new release of pip is available: 23.0.1 -> 23.3.2
Notice:  To update, run: pip install --upgrade pip
INFO:root:开始学习...
INFO:root:正在获取代理
INFO:root:获取到代理: ***
INFO:root:正在检查代理是否可用
INFO:root:代理可用
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/qndxxAutoStudy/qndxxAutoStudy/script.py", line 113, in <module>
    success, message = doStudy()
  File "/home/runner/work/qndxxAutoStudy/qndxxAutoStudy/script.py", line 44, in doStudy
    ret = qcshService.login(login_data)
  File "/home/runner/work/qndxxAutoStudy/qndxxAutoStudy/services/qcsh.py", line 40, in login
    ret = requests.get(QCSH_TOKEN_URL.format(open_id=open_id,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py", line [58](https://github.com/14790897/qndxxAutoStudy/actions/runs/7255948330/job/19767451113#step:4:59)9, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x[64](https://github.com/14790897/qndxxAutoStudy/actions/runs/7255948330/job/19767451113#step:4:65)/lib/python3.10/site-packages/requests/sessions.py", line [70](https://github.com/14790897/qndxxAutoStudy/actions/runs/7255948330/job/19767451113#step:4:71)3, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error: Process completed with exit code 1.

**Comment by 14790897** [comment]
workflow报错了，大佬有空麻烦看看

**Comment by vvbbnn00** [comment]
你好，这可能是网络环境的原因，多尝试几次即可。
若反复尝试都不行，可以尝试本地部署

**Comment by 14790897** [comment]
workflow成功了，谢谢大佬

**Comment by 14790897** [comment]
刚刚我把这个仓库添加到GitHub desktop，发现原来我不小心删掉了一点代码导致之前程序失败
